import path from 'node:path'
import {
  ROOT,
  copySkills,
  hooksForTool,
  removeIfExists,
  renderMcpConfig,
  resetDir,
  resolveModelMap,
  writeMarkdownSet,
  writeUtf8,
} from './common.mjs'

export const meta = {
  name: 'opencode',
  outputDirs: ['.opencode/agents', '.opencode/commands', '.opencode/skills', '.opencode/RULES.md', '.opencode/plugins/hooks.generated.ts', 'opencode.json'],
  mcpCapable: true,
}

export function renderOpencode(canonical) {
  writeMarkdownSet(canonical.personas, path.join(ROOT, '.opencode', 'agents'), { modelMap: resolveModelMap(canonical, 'opencode') })
  writeMarkdownSet(canonical.commands, path.join(ROOT, '.opencode', 'commands'))
  copySkills(canonical.skills, path.join(ROOT, '.opencode', 'skills'))
  writeUtf8(
    path.join(ROOT, '.opencode', 'RULES.md'),
    canonical.rules.map((rule) => rule.raw).join('\n\n'),
  )

  // Local plugins are auto-loaded from `.opencode/plugins` by OpenCode.
  const hooks = hooksForTool(canonical.hooks.hooks, 'opencode')
  const pluginSource = `/* eslint-disable */
// Generated by .agents/scripts/build.mjs
//
// OpenCode loads any JS/TS files in .opencode/plugins automatically.
// A plugin module exports one or more plugin functions.
// Each plugin function returns an object of hooks.

const canonicalHooks = ${JSON.stringify(hooks, null, 2)}

function compileMatcher(matcher) {
  if (!matcher) return null
  try {
    return new RegExp(String(matcher))
  } catch {
    return null
  }
}

function toolLabel(inputTool) {
  const t = String(inputTool || '')
  if (t === 'bash') return 'Bash'
  if (t === 'write') return 'Write'
  if (t === 'edit') return 'Edit'
  if (t === 'read') return 'Read'
  return t ? t[0].toUpperCase() + t.slice(1) : ''
}

function extractFilePath(args) {
  if (!args || typeof args !== 'object') return ''
  return String(args.filePath || args.file_path || args.path || args.file || args.target || '')
}

async function runHookCommand({ cwd, hook, env, stdin }) {
  const baseEnv = {
    ...process.env,
    ...env,
    HOOK_STDIN: stdin ?? '',
  }

  // Always provide stdin via pipe so jq-based hooks can consume tool input.
  const wrapped = 'printf \"%s\" \"$HOOK_STDIN\" | ' + String(hook.command || '')
  const proc = Bun.spawn({
    cmd: ['sh', '-lc', wrapped],
    cwd,
    env: baseEnv,
    stdout: 'pipe',
    stderr: 'pipe',
  })

  const exitCode = await proc.exited
  const stdout = proc.stdout ? await new Response(proc.stdout).text() : ''
  const stderr = proc.stderr ? await new Response(proc.stderr).text() : ''
  return { exitCode, stdout, stderr }
}

function filterByEvent(event) {
  return canonicalHooks.filter((hook) => hook && hook.event === event)
}

function filterByToolAndMatcher(event, toolName) {
  const label = toolLabel(toolName)
  return canonicalHooks.filter((hook) => {
    if (!hook || hook.event !== event) return false
    const rx = compileMatcher(hook.matcher)
    if (!rx) return true
    return rx.test(label)
  })
}

export const GeneratedHooks = async ({ directory, worktree }) => {
  const cwd = worktree || directory || process.cwd()

  return {
    event: async ({ event }) => {
      // Map canonical lifecycle events onto OpenCode's event stream.
      if (event?.type === 'session.created') {
        for (const hook of filterByEvent('session_start')) {
          await runHookCommand({ cwd, hook, env: { HOOK_EVENT: event.type }, stdin: '' })
        }
      }

      if (event?.type === 'tui.prompt.append') {
        for (const hook of filterByEvent('prompt_submit')) {
          await runHookCommand({ cwd, hook, env: { HOOK_EVENT: event.type }, stdin: '' })
        }
      }

      if (event?.type === 'session.idle' || event?.type === 'session.deleted') {
        for (const hook of filterByEvent('session_end')) {
          await runHookCommand({ cwd, hook, env: { HOOK_EVENT: event.type }, stdin: '' })
        }
      }
    },

    'tool.execute.before': async (input, output) => {
      const label = toolLabel(input?.tool)
      const args = output?.args || {}
      const filePath = extractFilePath(args)
      const command = typeof args.command === 'string' ? args.command : ''

      const stdin = JSON.stringify({
        tool_input: {
          tool: label,
          file_path: filePath,
          command,
        },
      })

      for (const hook of filterByToolAndMatcher('before_tool', input?.tool)) {
        const result = await runHookCommand({
          cwd,
          hook,
          env: {
            HOOK_EVENT: 'tool.execute.before',
            TOOL_NAME: label,
            TOOL_INPUT_COMMAND: command,
            TOOL_INPUT_FILE_PATH: filePath,
          },
          stdin,
        })

        if (result.exitCode !== 0) {
          const details = [result.stdout, result.stderr].filter(Boolean).join('\\n')
          const message = 'Hook blocked tool execution: ' + hook.id + (details ? '\\n' + details : '')
          throw new Error(message)
        }
      }
    },

    'tool.execute.after': async (input, output) => {
      const label = toolLabel(input?.tool)
      const args = output?.args || {}
      const filePath = extractFilePath(args)
      const command = typeof args.command === 'string' ? args.command : ''

      const stdin = JSON.stringify({
        tool_input: {
          tool: label,
          file_path: filePath,
          command,
        },
      })

      for (const hook of filterByToolAndMatcher('after_tool', input?.tool)) {
        await runHookCommand({
          cwd,
          hook,
          env: {
            HOOK_EVENT: 'tool.execute.after',
            TOOL_NAME: label,
            TOOL_INPUT_COMMAND: command,
            TOOL_INPUT_FILE_PATH: filePath,
          },
          stdin,
        })
      }
    },
  }
}
`

  const pluginsDir = path.join(ROOT, '.opencode', 'plugins')
  resetDir(pluginsDir)
  writeUtf8(path.join(pluginsDir, 'hooks.generated.ts'), pluginSource)

  // OpenCode project config lives at the project root. `.opencode/` is for agents/commands/skills/plugins only.
  removeIfExists(path.join(ROOT, '.opencode', 'opencode.json'))

  const config = {
    $schema: 'https://opencode.ai/config.json',
    instructions: ['AGENTS.md'],
  }

  if (canonical.mcpServers) {
    const mcpServers = renderMcpConfig(canonical.mcpServers, 'opencode')
    if (mcpServers) {
      config.mcp = mcpServers
    }
  }

  writeUtf8(path.join(ROOT, 'opencode.json'), JSON.stringify(config, null, 2) + '\n')

  // Prevent OpenCode plugin node_modules from being committed
  writeUtf8(path.join(ROOT, '.opencode', '.gitignore'), 'node_modules/\n')

  return { warnings: [] }
}
