#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import { randomUUID } from 'node:crypto'
import { load } from 'js-yaml'

const root = process.env.CLEARCUT_CONTRACT_ROOT || process.cwd()
const openapiPath = path.join(root, 'packages', 'contracts', 'openapi.yaml')
const generatedRoot = process.env.CLEARCUT_GENERATED_ROOT || path.join(root, 'packages', 'contracts', 'generated')
const tsOutDir = path.join(generatedRoot, 'typescript')
const pyOutDir = path.join(generatedRoot, 'python')

if (!fs.existsSync(openapiPath)) {
  console.error(`❌ openapi.yaml not found at ${openapiPath}`)
  process.exit(1)
}

const spec = load(fs.readFileSync(openapiPath, 'utf-8'))

const task10OperationIds = [
  'getClearanceItem',
  'assignClearanceItem',
  'bulkAssignClearanceItems',
  'recordEvidenceDecision',
  'setDisposition',
  'referClearanceItem',
  'acknowledgeReferral',
  'addComment',
  'replyToComment',
  'reviseComment',
  'listMonitoredSources',
  'listMonitoringChanges',
  'registerMonitoredSource',
]
const reportSchemaNames = [
  'ReportSnapshot',
  'ReportRelease',
  'ReportHistoryEntry',
  'ReportArtifactMetadata',
]
const reportSchemas = reportSchemaNames.map(name => {
  const schema = spec.components?.schemas?.[name]
  if (!schema) throw new Error(`Report schema component ${name} is required`)
  return { name, schema }
})
const diffSchemaRootNames = ['ScriptVersionDiff']
const task10PredeclaredNames = new Set([
  'ApiClientConfig',
  'ApiResult',
  'AuditRecord',
  'CreateInvitationRequest',
  'CreateOrganizationRequest',
  'CreateProjectRequest',
  'CreateSessionRequest',
  'DeploymentMetadata',
  'EvidenceClaim',
  'HealthResponse',
  'ISODateTime',
  'IdempotencyKey',
  'IdempotentCommandHeaders',
  'ImportArtifact',
  'Invitation',
  'ItemEvidence',
  'Job',
  'JobAttempt',
  'JobDispatchMetadata',
  'JobLifecycleEvent',
  'JobTarget',
  'Membership',
  'MonitoringPolicy',
  'MonitoringRun',
  'Notification',
  'Operations',
  'Organization',
  'ParseRun',
  'ParseWarning',
  'Project',
  'ProjectScript',
  'ProjectScriptLine',
  'ProjectScriptScene',
  'ReportArtifactMetadata',
  'ReportHistoryEntry',
  'ReportPreview',
  'ReportRelease',
  'ReportSnapshot',
  'RewriteProposal',
  'RunStatus',
  'SafeJobError',
  'ScriptVersion',
  'SessionContext',
  'SourceSnapshot',
  'UserRole',
  'UUIDv7',
])
const task10ExternalSchemaNames = new Set(['ISODateTime', 'UUIDv7'])
const task10SchemaNames = collectTask10OperationSchemaNames()
const task10Schemas = collectTask10Schemas(task10SchemaNames)
const diffSchemas = collectDiffSchemas(diffSchemaRootNames)

const doNotEditTs = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
 * Source: packages/contracts/openapi.yaml
 * Generated by: scripts/generate-clients.mjs
 */

`

const doNotEditPy = `"""
AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
Source: packages/contracts/openapi.yaml
Generated by: scripts/generate-clients.mjs
"""
# ruff: noqa
# fmt: off

`

// 1. Generate TypeScript Types & Client
let tsContent = `${doNotEditTs}export type UUIDv7 = string;
export type ISODateTime = string;

export type RunStatus =
  | 'queued'
  | 'claimed'
  | 'running'
  | 'retry_wait'
  | 'succeeded'
  | 'failed'
  | 'manual_retry'
  | 'cancelled';

export type UserRole = 'owner' | 'admin' | 'editor' | 'reviewer';

export interface JobDispatchMetadata {
  mode: 'disabled' | 'local' | 'cloud_tasks';
  durable: boolean;
}

export interface DeploymentMetadata {
  profile: 'local' | 'portable' | 'gcp';
  databaseConfigured: boolean;
  storageAdapter: 'filesystem' | 's3' | 'gcs';
  dispatchAdapter: 'local' | 'postgres' | 'cloud_tasks';
  dispatchEnabled: boolean;
  authenticationAdapter: 'builtin' | 'firebase';
  secretBackend: 'environment' | 'host' | 'secret_manager';
  paidProvidersEnabled: Array<'gemini' | 'parallel'>;
}

export interface HealthResponse {
  status: string;
  timestamp: ISODateTime;
  version: string;
  deployment: DeploymentMetadata;
  jobDispatch: JobDispatchMetadata;
}

export interface SessionContext {
  authenticated: boolean;
  userId?: UUIDv7 | null;
  email?: string | null;
  activeOrgId?: UUIDv7 | null;
  role?: UserRole | null;
}

export interface CreateSessionRequest {
  email: string;
  password: string;
}

export interface Organization {
  orgId: UUIDv7;
  name: string;
  slug: string;
  isDemo?: boolean;
  createdAt: ISODateTime;
}

export interface CreateOrganizationRequest {
  name: string;
  slug: string;
}

export interface Project {
  projectId: UUIDv7;
  orgId: UUIDv7;
  title: string;
  description?: string | null;
  productionType: string | null;
  productionStage: string | null;
  jurisdiction: string | null;
  targetLockDate: string | null;
  reviewBrief: string | null;
  isDemo?: boolean;
  createdAt: ISODateTime;
}

export interface CreateProjectRequest {
  title: string;
  description?: string | null;
  productionType?: string | null;
  productionStage?: string | null;
  jurisdiction?: string | null;
  targetLockDate?: string | null;
  reviewBrief?: string | null;
}

export interface Invitation {
  invitationId: UUIDv7;
  orgId: UUIDv7;
  email: string;
  role: UserRole;
  status: 'pending' | 'accepted' | 'declined' | 'revoked' | string;
  createdAt: ISODateTime;
}

export interface CreateInvitationRequest {
  email: string;
  role: UserRole;
  projectGrants?: UUIDv7[];
}

export interface Membership {
  membershipId: UUIDv7;
  orgId: UUIDv7;
  userId: UUIDv7;
  email?: string;
  role: UserRole;
  active: boolean;
  projectGrants?: UUIDv7[];
  createdAt: ISODateTime;
}

export interface ImportArtifact {
  artifactId: UUIDv7;
  projectId: UUIDv7;
  filename: string;
  contentType: string;
  sizeBytes: number;
  sha256: string;
  status: string;
  createdAt: ISODateTime;
}

export interface ParseWarning {
  code: string;
  line: number | null;
  message: string;
}

export interface ParseRun {
  runId: UUIDv7;
  artifactId: UUIDv7;
  status: RunStatus;
  parserName: string;
  parserVersion: string;
  warnings: ParseWarning[];
  sceneCount: number;
  elementCount: number;
  warningsAccepted: boolean;
  acceptedAt: ISODateTime | null;
  createdAt: ISODateTime;
  completedAt: ISODateTime;
}

export interface ScriptVersion {
  versionId: UUIDv7;
  scriptId: UUIDv7;
  projectId: UUIDv7;
  versionNumber: number;
  revisionLabel: string;
  title: string;
  ordinal: number;
  sourceArtifactId: UUIDv7 | null;
  parseRunId: UUIDv7 | null;
  sourceHash: string;
  parserVersion: string;
  sceneCount: number;
  elementCount: number;
  createdAt: ISODateTime;
}

export interface ProjectScriptLine {
  type: 'scene_heading' | 'action' | 'character' | 'parenthetical' | 'dialogue' | 'transition';
  text: string;
  flag?: string;
}

export interface ProjectScriptScene {
  number: number;
  slug: string;
  page: number | null;
  lines: ProjectScriptLine[];
}

export interface ProjectScript {
  title: string;
  version: string;
  versionId: UUIDv7;
  scenes: ProjectScriptScene[];
}

export interface SafeJobError {
  code: string;
  message: string;
  retryable: boolean;
}

export interface JobAttempt {
  number: number;
  status: 'running' | 'succeeded' | 'failed' | 'cancelled' | 'interrupted';
  startedAt: ISODateTime;
  completedAt: ISODateTime | null;
  error: SafeJobError | null;
}

export interface JobLifecycleEvent {
  action: 'cancelled' | 'retry_requested';
  actorId: UUIDv7;
  occurredAt: ISODateTime;
}

export interface JobTarget {
  type: 'project' | 'script_version' | 'clearance_item' | 'legacy_unknown';
  id: UUIDv7;
}

export interface Job {
  jobId: UUIDv7;
  status: RunStatus;
  jobType: string;
  target: JobTarget;
  canRetry: boolean;
  progress: number;
  stage: string;
  resultSummary: Record<string, unknown> | null;
  error: SafeJobError | null;
  attemptCount: number;
  attempts: JobAttempt[];
  history: JobLifecycleEvent[];
  availableAt: ISODateTime;
  createdAt: ISODateTime;
  updatedAt: ISODateTime;
}

export interface SourceSnapshot {
  snapshotId: UUIDv7;
  url: string;
  retrievedAt: ISODateTime;
  publisher: string;
  tier: string;
  excerpt?: string;
}

export interface EvidenceClaim {
  claimId: UUIDv7;
  snapshotId: UUIDv7;
  claimText: string;
  stance: string;
  confidence?: number;
}

export interface ItemEvidence {
  itemId: UUIDv7;
  claims: EvidenceClaim[];
  snapshots: SourceSnapshot[];
}

${generateTask10TsDeclarations()}

export interface RewriteProposal {
  proposalId: UUIDv7;
  itemId: UUIDv7;
  projectId?: UUIDv7;
  sourceVersionId?: UUIDv7;
  elementId?: UUIDv7;
  proposerId?: UUIDv7;
  proposerEmail?: string;
  approverId?: UUIDv7;
  originalText?: string;
  proposedText: string;
  rationale?: string;
  rejectionReason?: string;
  /** Present only once a separate materialization step binds the successor version. */
  resultingVersionId?: UUIDv7;
  itemVersion?: number;
  status: 'proposed' | 'approved' | 'rejected' | 'withdrawn' | 'materialized' | string;
  createdAt?: ISODateTime;
  updatedAt?: ISODateTime;
}

export interface MonitoringPolicy {
  projectId: UUIDv7;
  cadence: string;
  active: boolean;
  lastRunAt?: ISODateTime;
}

export interface MonitoringRun {
  runId: UUIDv7;
  projectId: UUIDv7;
  status: RunStatus;
  itemsChecked: number;
  changesDetected: number;
  createdAt: ISODateTime;
}

export interface Notification {
  notificationId: UUIDv7;
  orgId: UUIDv7;
  tier: 'urgent' | 'action' | 'informational';
  title: string;
  body: string;
  read: boolean;
  link?: string;
  blockedReason?: string;
  createdAt: ISODateTime;
}

export interface JudgeDimensionScore {
  dimension: string;
  status: 'scored' | 'incomplete' | 'not_applicable' | 'failed';
  score: number | null;
  rationale: string;
}

export interface DeterministicGateResult {
  gateName: string;
  passed: boolean;
  severity: string;
  details?: string;
}

export interface EvaluationProvenance {
  rubricVersion: string;
  promptVersion: string;
  policyVersion: string;
  requestedModel?: string;
  returnedModel?: string | null;
  inputSha256?: string;
  latencyMs?: number | null;
  totalTokens?: number | null;
  repairCount?: number;
}

export interface TrustEvaluation {
  evaluationId: UUIDv7;
  orgId: UUIDv7;
  projectId: UUIDv7;
  runId: UUIDv7;
  stage: 'detection' | 'research' | 'final';
  headlineScore: number | null;
  scoredDimensionsCount: number;
  blockersCount: number;
  critique?: string;
  dimensions: JudgeDimensionScore[];
  gates: DeterministicGateResult[];
  provenance: EvaluationProvenance;
  createdAt: ISODateTime;
}

export interface ProtectedConfiguration {
  configurationId: UUIDv7;
  orgId: UUIDv7;
  lifecycle: 'draft' | 'validated' | 'active' | 'superseded';
  label?: string;
  policyVersion: string;
  promptVersion: string;
  rationale?: string;
  validationIssues?: string[];
  activatedBy?: UUIDv7;
  activatedAt?: ISODateTime;
  validatedAt?: ISODateTime;
  supersededAt?: ISODateTime;
  createdAt: ISODateTime;
}

export interface LearningCandidate {
  candidateId: UUIDv7;
  orgId: UUIDv7;
  scope: 'query_phrasing' | 'retrieval_examples' | 'prompt_refinement' | 'org_preferences';
  stage: 'candidate' | 'shadow' | 'canary' | 'promoted' | 'rolled_back';
  title?: string;
  summary?: string;
  canaryPassRate: number;
  regressionCasesPassed: number;
  regressionCasesTotal: number;
  version: number;
  promotedAt?: ISODateTime;
  rolledBackAt?: ISODateTime;
  rollbackReason?: string;
  createdAt: ISODateTime;
}

export interface OrganizationSettings {
  orgId: UUIDv7;
  name: string;
  slug: string;
  jurisdiction?: string;
  defaultMonitoringCadence: 'off' | 'manual' | 'daily' | 'weekly';
  version: number;
}

export interface NotificationDeliveryPreference {
  channel: 'in_app' | 'email' | 'push';
}

export interface AuditRecord {
  recordId: UUIDv7;
  orgId: UUIDv7;
  projectId?: UUIDv7;
  eventType: string;
  actorId: UUIDv7;
  actorEmail?: string;
  payload?: Record<string, any>;
  receiptHash?: string;
  timestamp: ISODateTime;
}

export interface ReportPreview {
  projectId: UUIDv7;
  totalItems: number;
  clearedItems: number;
  flaggedItems: number;
  unresolvedRisk: number;
  categories?: Array<{ category?: string; count?: number }>;
}

${generateReportTsDeclarations()}

${generateDiffTsDeclarations()}

export type ApiResult<T, E extends ApiError = ApiError> =
  | { ok: true; value: T; meta?: ResponseMeta }
  | { ok: false; error: E };

export interface ApiClientConfig {
  baseUrl?: string;
  fetch?: typeof fetch;
}

async function request<T>(
  baseUrl: string,
  fetchFn: typeof fetch,
  method: string,
  path: string,
  options: {
    params?: Record<string, string | number | boolean | undefined>;
    query?: Record<string, unknown>;
    body?: unknown;
    bodyMediaType?: 'application/json' | 'multipart/form-data';
    headers?: Record<string, string>;
  } = {}
): Promise<ApiResult<T>> {
  let resolvedPath = path;
  if (options.params) {
    for (const [k, v] of Object.entries(options.params)) {
      resolvedPath = resolvedPath.replace(\`{\${k}}\`, encodeURIComponent(String(v)));
    }
  }

  const url = new URL(resolvedPath.startsWith('http') ? resolvedPath : \`\${baseUrl}\${resolvedPath}\`, typeof window !== 'undefined' ? window.location.origin : 'http://localhost:8000');

  if (options.query) {
    for (const [k, v] of Object.entries(options.query)) {
      if (v !== undefined) {
        url.searchParams.append(k, String(v));
      }
    }
  }

  const headers: Record<string, string> = {
    'Accept': 'application/json',
    ...(options.headers || {})
  };

  let requestBody: BodyInit | undefined;
  if (options.body !== undefined && options.bodyMediaType === 'multipart/form-data') {
    const form = new FormData();
    for (const [name, value] of Object.entries(options.body as Record<string, unknown>)) {
      if (value instanceof Blob) {
        form.append(name, value);
      } else if (value !== undefined && value !== null) {
        form.append(name, String(value));
      }
    }
    requestBody = form;
  } else if (options.body !== undefined) {
    headers['Content-Type'] = 'application/json';
    requestBody = JSON.stringify(options.body);
  }

  try {
    const res = await fetchFn(url.toString(), {
      method,
      headers,
      body: requestBody,
      credentials: 'include'
    });

    if (res.status === 204) {
      return { ok: true, value: undefined as unknown as T };
    }

    const json = await res.json().catch(() => undefined);

    if (res.ok && json === undefined) {
      return {
        ok: false,
        error: {
          code: 'internal_error',
          message: 'Successful response did not contain valid JSON',
          requestId: res.headers.get('x-request-id') || '',
          retryable: false
        }
      };
    }

    if (!res.ok) {
      const apiErr: ApiError = (json && json.error) ? json.error : {
        code: res.status === 401 ? 'authentication_required' : res.status === 403 ? 'permission_denied' : res.status === 404 ? 'not_found' : 'internal_error',
        message: (json && (json.message || json.detail)) || res.statusText || 'Request failed',
        requestId: (json && json.error && json.error.requestId) || res.headers.get('x-request-id') || '',
        retryable: res.status >= 500
      };
      return { ok: false, error: apiErr };
    }

    const data = (json && json.data !== undefined) ? json.data : json;
    const meta = (json && json.meta !== undefined) ? json.meta as ResponseMeta : undefined;
    return { ok: true, value: data as T, meta };
  } catch (err: unknown) {
    return {
      ok: false,
      error: {
        code: 'internal_error',
        message: err instanceof Error ? err.message : 'Network request failed',
        requestId: '',
        retryable: true
      }
    };
  }
}
`

// Generate operation-specific request and response types from OpenAPI.
function resolveRef(ref) {
  return ref
    .replace(/^#\//, '')
    .split('/')
    .reduce((value, key) => value?.[key], spec)
}

function resolveNode(node) {
  if (node && node.$ref) {
    return resolveRef(node.$ref)
  }
  return node
}

function propertyName(name) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name)
}

function tsEnumMember(value) {
  if (typeof value !== 'string') return JSON.stringify(value)
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

function schemaToTs(schema) {
  if (!schema) return 'unknown'
  if (schema.$ref) return schema.$ref.split('/').at(-1)

  let type
  if (schema.enum) {
    type = schema.enum.map(tsEnumMember).join(' | ')
  } else if (schema.oneOf || schema.anyOf) {
    type = (schema.oneOf || schema.anyOf).map(schemaToTs).join(' | ')
  } else if (schema.allOf) {
    type = schema.allOf.map(schemaToTs).join(' & ')
  } else if (schema.type === 'null') {
    type = 'null'
  } else if (schema.type === 'string') {
    type = schema.format === 'binary' ? 'Blob' : 'string'
  } else if (schema.type === 'integer' || schema.type === 'number') {
    type = 'number'
  } else if (schema.type === 'boolean') {
    type = 'boolean'
  } else if (schema.type === 'array') {
    type = `Array<${schemaToTs(schema.items)}>`
  } else if (schema.type === 'object' || schema.properties || schema.additionalProperties) {
    const required = new Set(schema.required || [])
    const properties = Object.entries(schema.properties || {}).map(
      ([name, propertySchema]) =>
        `${propertyName(name)}${required.has(name) ? '' : '?'}: ${schemaToTs(propertySchema)}`,
    )
    if (properties.length > 0) {
      type = `{ ${properties.join('; ')} }`
      if (schema.additionalProperties) {
        const additionalType = schema.additionalProperties === true
          ? 'unknown'
          : schemaToTs(schema.additionalProperties)
        type = `${type} & Record<string, ${additionalType}>`
      }
    } else if (schema.additionalProperties) {
      const additionalType = schema.additionalProperties === true
        ? 'unknown'
        : schemaToTs(schema.additionalProperties)
      type = `Record<string, ${additionalType}>`
    } else {
      type = 'Record<string, never>'
    }
  } else {
    type = 'unknown'
  }

  return schema.nullable ? `${type} | null` : type
}

function componentSchemaName(ref) {
  const prefix = '#/components/schemas/'
  if (typeof ref !== 'string' || !ref.startsWith(prefix)) {
    throw new Error(`Task 10 schema reference ${String(ref)} must target components.schemas`)
  }
  return ref
    .slice(prefix.length)
    .replaceAll('~1', '/')
    .replaceAll('~0', '~')
}

function referencedSchemaNames(node, names = new Set()) {
  if (Array.isArray(node)) {
    for (const value of node) referencedSchemaNames(value, names)
    return names
  }
  if (!node || typeof node !== 'object') return names

  if ('$ref' in node) names.add(componentSchemaName(node.$ref))
  for (const key of Object.keys(node).sort()) {
    if (key !== '$ref') referencedSchemaNames(node[key], names)
  }
  return names
}

function classifyTask10Schema(schema) {
  if (Array.isArray(schema.enum)) return 'enum'
  if (schema.type === 'object' || schema.properties) return 'object'
  return 'alias'
}

function collectTask10OperationSchemaNames() {
  const operationsById = new Map()
  for (const pathItem of Object.values(spec.paths || {})) {
    for (const method of ['get', 'post', 'put', 'delete', 'patch']) {
      const operation = pathItem[method]
      if (!operation || !task10OperationIds.includes(operation.operationId)) continue
      if (operationsById.has(operation.operationId)) {
        throw new Error(`Task 10 operation ${operation.operationId} is declared more than once`)
      }
      operationsById.set(operation.operationId, operation)
    }
  }

  const missingOperationIds = task10OperationIds.filter(id => !operationsById.has(id))
  if (missingOperationIds.length > 0) {
    throw new Error(`Task 10 operations are required: ${missingOperationIds.join(', ')}`)
  }

  const names = new Set()
  const collectContentSchemaNames = content => {
    const schema = content?.['application/json']?.schema
    if (!schema) return
    for (const name of [...referencedSchemaNames(schema)].sort()) names.add(name)
  }

  for (const operationId of task10OperationIds) {
    const requestBody = resolveNode(operationsById.get(operationId).requestBody)
    collectContentSchemaNames(requestBody?.content)
  }
  for (const operationId of task10OperationIds) {
    const operation = operationsById.get(operationId)
    for (const statusCode of Object.keys(operation.responses || {}).sort()) {
      const response = resolveNode(operation.responses[statusCode])
      collectContentSchemaNames(response?.content)
    }
  }

  return [...names]
}

function collectTask10Schemas(rootNames) {
  const ordered = []
  const state = new Map()

  function visit(name) {
    if (task10ExternalSchemaNames.has(name)) return
    if (task10PredeclaredNames.has(name)) {
      throw new Error(`Task 10 schema ${name} collides with predeclared name`)
    }
    if (state.get(name) === 'complete' || state.get(name) === 'visiting') return

    const schema = spec.components?.schemas?.[name]
    if (!schema) throw new Error(`Task 10 schema component ${name} is required`)
    state.set(name, 'visiting')
    for (const dependencyName of [...referencedSchemaNames(schema)].sort()) {
      visit(dependencyName)
    }
    state.set(name, 'complete')
    ordered.push({ name, schema, kind: classifyTask10Schema(schema) })
  }

  for (const rootName of rootNames) visit(rootName)
  return ordered
}

// Collect Task 4 revision-diff schemas in dependency order (enums before the
// objects that reference them). These schemas are external to the Task 10 set;
// UUIDv7/ISODateTime are predeclared aliases and are not re-emitted.
function collectDiffSchemas(rootNames) {
  const external = new Set(['ISODateTime', 'UUIDv7'])
  const ordered = []
  const state = new Map()

  function visit(name) {
    if (external.has(name)) return
    if (state.get(name) === 'complete' || state.get(name) === 'visiting') return

    const schema = spec.components?.schemas?.[name]
    if (!schema) throw new Error(`Diff schema component ${name} is required`)
    state.set(name, 'visiting')
    for (const dependencyName of [...referencedSchemaNames(schema)].sort()) {
      visit(dependencyName)
    }
    state.set(name, 'complete')
    ordered.push({ name, schema, kind: classifyTask10Schema(schema) })
  }

  for (const rootName of rootNames) visit(rootName)
  return ordered
}

function generateTask10TsObjectDeclaration(name, schema) {
  const required = new Set(schema.required || [])
  const fields = Object.entries(schema.properties || {}).map(
    ([fieldName, fieldSchema]) =>
      `  ${propertyName(fieldName)}${required.has(fieldName) ? '' : '?'}: ${schemaToTs(fieldSchema)};`,
  )
  return `export interface ${name} {\n${fields.join('\n')}\n}\n`
}

function generateTask10TsDeclarations() {
  return task10Schemas.map(({ name, schema, kind }) => {
    if (name === 'ErrorEnvelope') {
      const errorSchema = schema.properties?.error
      if (!errorSchema || (errorSchema.type !== 'object' && !errorSchema.properties)) {
        throw new Error('Task 10 ErrorEnvelope.error must be an object schema')
      }
      const envelopeSchema = {
        ...schema,
        properties: {
          ...schema.properties,
          error: { $ref: '#/components/schemas/ApiError' },
        },
      }
      return `${generateTask10TsObjectDeclaration('ApiError', errorSchema)}\n${generateTask10TsObjectDeclaration(name, envelopeSchema)}`
    }
    if (kind !== 'object') {
      return `export type ${name} = ${schemaToTs(schema)};\n`
    }
    return generateTask10TsObjectDeclaration(name, schema)
  }).join('\n')
}

function generateReportTsDeclarations() {
  return reportSchemas
    .map(({ name, schema }) => generateTask10TsObjectDeclaration(name, schema))
    .join('\n')
}

function generateDiffTsDeclarations() {
  return diffSchemas.map(({ name, schema, kind }) => {
    if (kind !== 'object') {
      return `export type ${name} = ${schemaToTs(schema)};\n`
    }
    return generateTask10TsObjectDeclaration(name, schema)
  }).join('\n')
}

function successType(operation) {
  const success = Object.entries(operation.responses || {}).find(([statusCode]) => /^2\d\d$/.test(statusCode))
  if (!success) return 'unknown'
  const [statusCode, unresolvedResponse] = success
  if (statusCode === '204') return 'void'
  const response = resolveNode(unresolvedResponse)
  const responseSchema = response?.content?.['application/json']?.schema
  if (!responseSchema) return 'unknown'
  const resolvedSchema = resolveNode(responseSchema)
  const dataSchema = resolvedSchema?.properties?.data
  return schemaToTs(dataSchema || responseSchema)
}

const operationsList = []
const paths = spec.paths || {}
for (const [pathKey, pathItem] of Object.entries(paths)) {
  for (const method of ['get', 'post', 'put', 'delete', 'patch']) {
    if (pathItem[method]) {
      const op = pathItem[method]
      const parameters = [...(pathItem.parameters || []), ...(op.parameters || [])].map(resolveNode)
      const pathParameterNames = (pathKey.match(/{([^}]+)}/g) || []).map(value => value.slice(1, -1))
      const pathParams = pathParameterNames.map(name => {
        const parameter = parameters.find(candidate => candidate?.in === 'path' && candidate.name === name)
        return { name, type: schemaToTs(parameter?.schema) }
      })
      const queryParams = parameters
        .filter(parameter => parameter?.in === 'query')
        .map(parameter => ({
          name: parameter.name,
          required: parameter.required === true,
          type: schemaToTs(parameter.schema),
        }))
      const headerParams = parameters
        .filter(parameter => parameter?.in === 'header')
        .map(parameter => ({
          name: parameter.name,
          required: parameter.required === true,
          type: schemaToTs(parameter.schema),
        }))
      const requestBody = resolveNode(op.requestBody)
      const requestContent = requestBody?.content || {}
      const bodyMediaType = requestContent['application/json']
        ? 'application/json'
        : requestContent['multipart/form-data']
          ? 'multipart/form-data'
          : null
      const requestSchema = bodyMediaType ? requestContent[bodyMediaType]?.schema : null

      operationsList.push({
        id: op.operationId,
        method: method.toUpperCase(),
        path: pathKey,
        summary: op.summary || '',
        pathParams,
        queryParams,
        headerParams,
        bodyType: requestSchema ? schemaToTs(requestSchema) : null,
        bodyMediaType,
        bodyRequired: requestBody?.required === true,
        responseType: successType(op),
      })
    }
  }
}

tsContent += `\nexport interface Operations {\n`
for (const op of operationsList) {
  tsContent += `  ${op.id}: { method: '${op.method}'; path: '${op.path}' };\n`
}
tsContent += `}\n\n`

tsContent += `export function createApiClient(config: ApiClientConfig = {}) {\n`
tsContent += `  const baseUrl = config.baseUrl || '';\n`
tsContent += `  const fetchFn = config.fetch || (typeof window !== 'undefined' ? window.fetch.bind(window) : fetch);\n\n`
tsContent += `  return {\n`

for (const op of operationsList) {
  const queryRequired = op.queryParams.some(parameter => parameter.required)
  const headersRequired = op.headerParams.some(parameter => parameter.required)
  const argsRequired = op.pathParams.length > 0 || queryRequired || headersRequired || op.bodyRequired

  tsContent += `    /** ${op.summary} */\n`
  tsContent += `    ${op.id}: async (\n`
  tsContent += `      args${argsRequired ? '' : '?'}: {\n`
  if (op.pathParams.length > 0) {
    tsContent += `        params: { ${op.pathParams.map(parameter => `${propertyName(parameter.name)}: ${parameter.type}`).join('; ')} };\n`
  }
  if (op.queryParams.length > 0) {
    const queryType = op.queryParams
      .map(parameter => `${propertyName(parameter.name)}${parameter.required ? '' : '?'}: ${parameter.type}`)
      .join('; ')
    tsContent += `        query${queryRequired ? '' : '?'}: { ${queryType} };\n`
  }
  if (op.bodyType) {
    tsContent += `        body${op.bodyRequired ? '' : '?'}: ${op.bodyType};\n`
  }
  if (op.headerParams.length > 0) {
    const headerType = op.headerParams
      .map(parameter => `${JSON.stringify(parameter.name)}${parameter.required ? '' : '?'}: ${parameter.type}`)
      .join('; ')
    tsContent += `        headers${headersRequired ? '' : '?'}: { ${headerType} } & Record<string, string>;\n`
  } else {
    tsContent += `        headers?: Record<string, string>;\n`
  }
  tsContent += `      }\n`
  tsContent += `    ): Promise<ApiResult<${op.responseType}>> => {\n`
  tsContent += `      const headers: Record<string, string> = { ...(args?.headers || {}) };\n`
  tsContent += `      return request<${op.responseType}>(baseUrl, fetchFn, '${op.method}', '${op.path}', {\n`
  if (op.pathParams.length > 0) {
    tsContent += `        params: args?.params,\n`
  }
  if (op.queryParams.length > 0) {
    tsContent += `        query: args?.query,\n`
  }
  if (op.bodyType) {
    tsContent += `        body: args?.body,\n`
    tsContent += `        bodyMediaType: '${op.bodyMediaType}',\n`
  }
  tsContent += `        headers,\n`
  tsContent += `      });\n`
  tsContent += `    },\n\n`
}

tsContent += `  };\n`
tsContent += `}\n\n`
tsContent += `export const api = createApiClient();\n`

function pythonIdentifier(name) {
  const parts = name.split(/[^A-Za-z0-9_]+/).filter(Boolean)
  const identifier = parts
    .map((part, index) => index === 0
      ? `${part[0].toLowerCase()}${part.slice(1)}`
      : `${part[0].toUpperCase()}${part.slice(1)}`)
    .join('')
  if (!identifier || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(identifier)) {
    throw new Error(`Cannot derive Python identifier from ${name}`)
  }
  return identifier
}

function schemaToPython(schema) {
  if (!schema) return 'Any'
  if (schema.$ref) return schema.$ref.split('/').at(-1)

  if (schema.anyOf) {
    const nonNull = schema.anyOf.filter(candidate => candidate.type !== 'null')
    const hasNull = nonNull.length !== schema.anyOf.length
    if (hasNull && nonNull.length === 1) {
      return `Optional[${schemaToPython(nonNull[0])}]`
    }
  }

  let type
  if (schema.enum) {
    type = `Literal[${schema.enum.map(value => JSON.stringify(value)).join(', ')}]`
  } else if (schema.type === 'string') {
    type = 'str'
  } else if (schema.type === 'integer') {
    type = 'int'
  } else if (schema.type === 'number') {
    type = 'float'
  } else if (schema.type === 'boolean') {
    type = 'bool'
  } else if (schema.type === 'array') {
    type = `List[${schemaToPython(schema.items)}]`
  } else if (schema.type === 'object' || schema.properties || schema.additionalProperties) {
    const valueType = schema.additionalProperties && schema.additionalProperties !== true
      ? schemaToPython(schema.additionalProperties)
      : 'Any'
    type = `Dict[str, ${valueType}]`
  } else {
    type = 'Any'
  }

  const fieldConstraints = []
  if (schema.minLength !== undefined) fieldConstraints.push(`min_length=${schema.minLength}`)
  if (schema.maxLength !== undefined) fieldConstraints.push(`max_length=${schema.maxLength}`)
  if (schema.pattern !== undefined) fieldConstraints.push(`pattern=${JSON.stringify(schema.pattern)}`)
  if (schema.minimum !== undefined) fieldConstraints.push(`ge=${schema.minimum}`)
  if (schema.maximum !== undefined) fieldConstraints.push(`le=${schema.maximum}`)
  if (schema.minItems !== undefined) fieldConstraints.push(`min_length=${schema.minItems}`)
  if (schema.maxItems !== undefined) fieldConstraints.push(`max_length=${schema.maxItems}`)

  const metadata = []
  if (fieldConstraints.length > 0) metadata.push(`Field(${fieldConstraints.join(', ')})`)
  if (schema.type === 'array' && schema.uniqueItems === true) {
    metadata.push('AfterValidator(_require_unique_items)')
  }
  return metadata.length > 0 ? `Annotated[${type}, ${metadata.join(', ')}]` : type
}

function nodeUsesUniqueItems(node) {
  if (Array.isArray(node)) return node.some(nodeUsesUniqueItems)
  if (!node || typeof node !== 'object') return false
  if (node.type === 'array' && node.uniqueItems === true) return true
  return Object.values(node).some(nodeUsesUniqueItems)
}

function task10UsesUniqueItems() {
  return task10Schemas.some(({ schema }) => nodeUsesUniqueItems(schema))
}

function generatePythonModel(name, schema) {
  if (schema.type !== 'object' && !schema.properties) {
    throw new Error(`Task 10 model ${name} must be an object schema`)
  }
  const required = new Set(schema.required || [])
  const lines = [`class ${name}(BaseModel):`]
  if (schema.additionalProperties === false) {
    lines.push('    model_config = ConfigDict(extra="forbid")', '')
  }
  for (const [fieldName, fieldSchema] of Object.entries(schema.properties || {})) {
    const isRequired = required.has(fieldName)
    const resolvedType = schemaToPython(fieldSchema)
    const fieldType = isRequired || resolvedType.startsWith('Optional[')
      ? resolvedType
      : `Optional[${resolvedType}]`
    lines.push(`    ${pythonIdentifier(fieldName)}: ${fieldType}${isRequired ? '' : ' = None'}`)
  }
  if (lines.length === 1) lines.push('    pass')
  return lines.join('\n')
}

function generateReportPythonDeclarations() {
  return reportSchemas
    .map(({ name, schema }) => generatePythonModel(name, schema))
    .join('\n\n')
}

function generateDiffPythonDeclarations() {
  return diffSchemas
    .map(({ name, schema, kind }) => kind === 'object'
      ? generatePythonModel(name, schema)
      : `${name} = ${schemaToPython(schema)}`)
    .join('\n\n')
}

function generateTask10ErrorPythonDeclarations(schema) {
  const errorSchema = schema.properties?.error
  if (!errorSchema || (errorSchema.type !== 'object' && !errorSchema.properties)) {
    throw new Error('Task 10 ErrorEnvelope.error must be an object schema')
  }

  const declarations = []
  const payloadProperties = { ...errorSchema.properties }
  if (payloadProperties.code) {
    declarations.push(`ErrorCode = ${schemaToPython(payloadProperties.code)}`)
    payloadProperties.code = { $ref: '#/components/schemas/ErrorCode' }
  }

  const detailsSchema = payloadProperties.details
  if (detailsSchema?.type === 'array' && detailsSchema.items
      && (detailsSchema.items.type === 'object' || detailsSchema.items.properties)) {
    declarations.push(generatePythonModel('ErrorDetail', detailsSchema.items))
    payloadProperties.details = {
      ...detailsSchema,
      items: { $ref: '#/components/schemas/ErrorDetail' },
    }
  }

  declarations.push(generatePythonModel('ErrorPayload', {
    ...errorSchema,
    properties: payloadProperties,
  }))
  declarations.push(generatePythonModel('ErrorEnvelope', {
    ...schema,
    properties: {
      ...schema.properties,
      error: { $ref: '#/components/schemas/ErrorPayload' },
    },
  }))
  return declarations
}

function generateTask10PythonDeclarations() {
  const declarations = []
  if (task10UsesUniqueItems()) {
    declarations.push(`def _require_unique_items(value: List[Any]) -> List[Any]:
    if len(value) != len(set(value)):
        raise ValueError("Items must be unique")
    return value`)
  }

  for (const { name, schema, kind } of task10Schemas) {
    if (name === 'ErrorEnvelope') {
      declarations.push(...generateTask10ErrorPythonDeclarations(schema))
    } else {
      declarations.push(kind === 'object'
        ? generatePythonModel(name, schema)
        : `${name} = ${schemaToPython(schema)}`)
    }
  }

  const header = spec.components?.parameters?.RequiredIdempotencyKey
  if (!header?.schema || !header.name) {
    throw new Error('RequiredIdempotencyKey parameter is required for Task 10 generation')
  }
  const headerType = schemaToPython(header.schema)
  const headerField = pythonIdentifier(header.name)
  declarations.push(`IdempotencyKey = ${headerType}`)
  declarations.push(`class IdempotentCommandHeaders(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    ${headerField}: ${header.required === true ? 'IdempotencyKey' : 'Optional[IdempotencyKey]'} = Field(${header.required === true ? '' : 'default=None, '}alias=${JSON.stringify(header.name)})`)

  return `${declarations.join('\n\n')}\n`
}

// 2. Generate Python Types & Client
const uuidV7Pattern = spec.components?.schemas?.UUIDv7?.pattern
if (!uuidV7Pattern) {
  throw new Error('UUIDv7 schema pattern is required for generated Python validation')
}

let pyContent = `${doNotEditPy}from __future__ import annotations
from datetime import date
from typing import Annotated, Literal, Optional, List, Dict, Any
from pydantic import AfterValidator, BaseModel, ConfigDict, Field

UUIDv7 = Annotated[str, Field(pattern=${JSON.stringify(uuidV7Pattern)})]
ISODateTime = str

RunStatus = Literal[
    "queued",
    "claimed",
    "running",
    "retry_wait",
    "succeeded",
    "failed",
    "manual_retry",
    "cancelled",
]

UserRole = Literal["owner", "admin", "editor", "reviewer"]

class JobDispatchMetadata(BaseModel):
    mode: Literal["disabled", "local", "cloud_tasks"]
    durable: bool

class DeploymentMetadata(BaseModel):
    profile: Literal["local", "portable", "gcp"]
    databaseConfigured: bool
    storageAdapter: Literal["filesystem", "s3", "gcs"]
    dispatchAdapter: Literal["local", "postgres", "cloud_tasks"]
    dispatchEnabled: bool
    authenticationAdapter: Literal["builtin", "firebase"]
    secretBackend: Literal["environment", "host", "secret_manager"]
    paidProvidersEnabled: List[Literal["gemini", "parallel"]]

class HealthResponse(BaseModel):
    status: str
    timestamp: ISODateTime
    version: str
    deployment: DeploymentMetadata
    jobDispatch: JobDispatchMetadata

class SessionContext(BaseModel):
    authenticated: bool
    userId: Optional[UUIDv7] = None
    email: Optional[str] = None
    activeOrgId: Optional[UUIDv7] = None
    role: Optional[UserRole] = None

class CreateSessionRequest(BaseModel):
    email: str
    password: str

class Organization(BaseModel):
    orgId: UUIDv7
    name: str
    slug: str
    isDemo: Optional[bool] = False
    createdAt: ISODateTime

class CreateOrganizationRequest(BaseModel):
    name: str
    slug: str

class Project(BaseModel):
    projectId: UUIDv7
    orgId: UUIDv7
    title: str
    description: Optional[str] = None
    productionType: Optional[str]
    productionStage: Optional[str]
    jurisdiction: Optional[str]
    targetLockDate: Optional[date]
    reviewBrief: Optional[str]
    isDemo: Optional[bool] = False
    createdAt: ISODateTime

class CreateProjectRequest(BaseModel):
    title: str
    description: Optional[str] = None
    productionType: Optional[str] = None
    productionStage: Optional[str] = None
    jurisdiction: Optional[str] = None
    targetLockDate: Optional[date] = None
    reviewBrief: Optional[str] = None

class Invitation(BaseModel):
    invitationId: UUIDv7
    orgId: UUIDv7
    email: str
    role: UserRole
    status: str
    createdAt: ISODateTime

class CreateInvitationRequest(BaseModel):
    email: str
    role: UserRole
    projectGrants: Optional[List[UUIDv7]] = None

class Membership(BaseModel):
    membershipId: UUIDv7
    orgId: UUIDv7
    userId: UUIDv7
    email: Optional[str] = None
    role: UserRole
    active: bool
    projectGrants: Optional[List[UUIDv7]] = None
    createdAt: ISODateTime

class ImportArtifact(BaseModel):
    artifactId: UUIDv7
    projectId: UUIDv7
    filename: str
    contentType: str
    sizeBytes: int
    sha256: str
    status: str
    createdAt: ISODateTime

class ParseWarning(BaseModel):
    code: str
    line: Optional[int]
    message: str

class ParseRun(BaseModel):
    runId: UUIDv7
    artifactId: UUIDv7
    status: RunStatus
    parserName: str
    parserVersion: str
    warnings: List[ParseWarning]
    sceneCount: int
    elementCount: int
    warningsAccepted: bool
    acceptedAt: Optional[ISODateTime]
    createdAt: ISODateTime
    completedAt: ISODateTime

class ScriptVersion(BaseModel):
    versionId: UUIDv7
    scriptId: UUIDv7
    projectId: UUIDv7
    versionNumber: int
    revisionLabel: str
    title: str
    ordinal: int
    sourceArtifactId: Optional[UUIDv7]
    parseRunId: Optional[UUIDv7]
    sourceHash: str
    parserVersion: str
    sceneCount: int
    elementCount: int
    createdAt: ISODateTime

class ProjectScriptLine(BaseModel):
    type: str
    text: str
    flag: Optional[str] = None

class ProjectScriptScene(BaseModel):
    number: int
    slug: str
    page: Optional[int]
    lines: List[ProjectScriptLine]

class ProjectScript(BaseModel):
    title: str
    version: str
    versionId: UUIDv7
    scenes: List[ProjectScriptScene]

class SafeJobError(BaseModel):
    code: str
    message: str
    retryable: bool

class JobAttempt(BaseModel):
    number: int
    status: Literal["running", "succeeded", "failed", "cancelled", "interrupted"]
    startedAt: ISODateTime
    completedAt: Optional[ISODateTime]
    error: Optional[SafeJobError]

class JobLifecycleEvent(BaseModel):
    action: Literal["cancelled", "retry_requested"]
    actorId: UUIDv7
    occurredAt: ISODateTime

class JobTarget(BaseModel):
    type: Literal["project", "script_version", "clearance_item", "legacy_unknown"]
    id: UUIDv7

class Job(BaseModel):
    jobId: UUIDv7
    status: RunStatus
    jobType: str
    target: JobTarget
    canRetry: bool
    progress: float
    stage: str
    resultSummary: Optional[Dict[str, Any]]
    error: Optional[SafeJobError]
    attemptCount: int
    attempts: List[JobAttempt]
    history: List[JobLifecycleEvent]
    availableAt: ISODateTime
    createdAt: ISODateTime
    updatedAt: ISODateTime

${generateTask10PythonDeclarations()}
class SourceSnapshot(BaseModel):
    snapshotId: UUIDv7
    url: str
    retrievedAt: ISODateTime
    publisher: str
    tier: str
    excerpt: Optional[str] = None

class EvidenceClaim(BaseModel):
    claimId: UUIDv7
    snapshotId: UUIDv7
    claimText: str
    stance: str
    confidence: Optional[float] = None

class ItemEvidence(BaseModel):
    itemId: UUIDv7
    claims: List[EvidenceClaim] = []
    snapshots: List[SourceSnapshot] = []

class RewriteProposal(BaseModel):
    proposalId: UUIDv7
    itemId: UUIDv7
    projectId: Optional[UUIDv7] = None
    sourceVersionId: Optional[UUIDv7] = None
    elementId: Optional[UUIDv7] = None
    proposerId: Optional[UUIDv7] = None
    proposerEmail: Optional[str] = None
    approverId: Optional[UUIDv7] = None
    originalText: Optional[str] = None
    proposedText: str
    rationale: Optional[str] = None
    rejectionReason: Optional[str] = None
    resultingVersionId: Optional[UUIDv7] = None
    itemVersion: Optional[int] = None
    status: str
    createdAt: Optional[ISODateTime] = None
    updatedAt: Optional[ISODateTime] = None

class MonitoringPolicy(BaseModel):
    projectId: UUIDv7
    cadence: str
    active: bool
    lastRunAt: Optional[ISODateTime] = None

class MonitoringRun(BaseModel):
    runId: UUIDv7
    projectId: UUIDv7
    status: RunStatus
    itemsChecked: int
    changesDetected: int
    createdAt: ISODateTime

class Notification(BaseModel):
    notificationId: UUIDv7
    orgId: UUIDv7
    title: str
    body: str
    read: bool
    link: Optional[str] = None
    createdAt: ISODateTime

class AuditRecord(BaseModel):
    recordId: UUIDv7
    orgId: UUIDv7
    projectId: Optional[UUIDv7] = None
    eventType: str
    actorId: UUIDv7
    actorEmail: Optional[str] = None
    payload: Optional[Dict[str, Any]] = None
    receiptHash: Optional[str] = None
    timestamp: ISODateTime

class ReportPreview(BaseModel):
    projectId: UUIDv7
    totalItems: int
    clearedItems: int
    flaggedItems: int
    unresolvedRisk: int
    categories: Optional[List[Dict[str, Any]]] = None

${generateReportPythonDeclarations()}

${generateDiffPythonDeclarations()}
`

function validateGeneratedOutput(label, content, header, requiredDeclaration) {
  if (typeof content !== 'string' || !content.startsWith(header) || !content.includes(requiredDeclaration)) {
    throw new Error(`${label} generated output failed validation`)
  }
}

function temporarySiblingPath(destination, kind) {
  return path.join(
    path.dirname(destination),
    `.${path.basename(destination)}.${process.pid}.${randomUUID()}.${kind}`,
  )
}

function publishGeneratedOutputs(outputs) {
  const staged = []
  const backups = []
  const promoted = new Set()

  try {
    for (const output of outputs) {
      fs.mkdirSync(path.dirname(output.destination), { recursive: true })
      const temporaryPath = temporarySiblingPath(output.destination, 'tmp')
      fs.writeFileSync(temporaryPath, output.content, { encoding: 'utf-8', flag: 'wx' })
      staged.push({ ...output, temporaryPath })
    }

    for (const output of outputs) {
      if (!fs.existsSync(output.destination)) continue
      const backupPath = temporarySiblingPath(output.destination, 'backup')
      fs.copyFileSync(output.destination, backupPath, fs.constants.COPYFILE_EXCL)
      backups.push({ destination: output.destination, backupPath })
    }

    for (const output of staged) {
      fs.renameSync(output.temporaryPath, output.destination)
      promoted.add(output.destination)
    }
  } catch (error) {
    for (const output of [...outputs].reverse()) {
      const backup = backups.find(candidate => candidate.destination === output.destination)
      if (backup && fs.existsSync(backup.backupPath)) {
        fs.renameSync(backup.backupPath, output.destination)
      } else if (promoted.has(output.destination)) {
        fs.rmSync(output.destination, { force: true })
      }
    }
    throw error
  } finally {
    for (const output of staged) fs.rmSync(output.temporaryPath, { force: true })
    for (const backup of backups) fs.rmSync(backup.backupPath, { force: true })
  }
}

const tsOutputPath = path.join(tsOutDir, 'index.ts')
const pyOutputPath = path.join(pyOutDir, '__init__.py')
validateGeneratedOutput('TypeScript', tsContent, doNotEditTs, 'export function createApiClient')
validateGeneratedOutput('Python', pyContent, doNotEditPy, 'class ErrorEnvelope(BaseModel):')
publishGeneratedOutputs([
  { destination: tsOutputPath, content: tsContent },
  { destination: pyOutputPath, content: pyContent },
])
console.log('✅ Generated TypeScript client contracts at', tsOutputPath)
console.log('✅ Generated Python client contracts at', pyOutputPath)
