#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import { load } from 'js-yaml'

const root = process.cwd()
const openapiPath = path.join(root, 'packages', 'contracts', 'openapi.yaml')
const tsOutDir = path.join(root, 'packages', 'contracts', 'generated', 'typescript')
const pyOutDir = path.join(root, 'packages', 'contracts', 'generated', 'python')

if (!fs.existsSync(openapiPath)) {
  console.error(`❌ openapi.yaml not found at ${openapiPath}`)
  process.exit(1)
}

const spec = load(fs.readFileSync(openapiPath, 'utf-8'))

const doNotEditTs = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
 * Source: packages/contracts/openapi.yaml
 * Generated by: scripts/generate-clients.mjs
 */

`

const doNotEditPy = `"""
AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
Source: packages/contracts/openapi.yaml
Generated by: scripts/generate-clients.mjs
"""

`

// 1. Generate TypeScript Types & Client
fs.mkdirSync(tsOutDir, { recursive: true })

let tsContent = `${doNotEditTs}export type UUIDv7 = string;\nexport type ISODateTime = string;\n\n`

tsContent += `export type RunStatus =\n  | 'queued'\n  | 'claimed'\n  | 'running'\n  | 'retry_wait'\n  | 'succeeded'\n  | 'failed'\n  | 'manual_retry'\n  | 'cancelled';\n\n`

tsContent += `export type UserRole = 'owner' | 'admin' | 'editor' | 'reviewer';\n\n`

tsContent += `export interface HealthResponse {\n  status: string;\n  timestamp: ISODateTime;\n  version: string;\n}\n\n`

tsContent += `export interface SessionContext {\n  authenticated: boolean;\n  userId?: UUIDv7;\n  email?: string;\n  activeOrgId?: UUIDv7;\n  role?: UserRole;\n}\n\n`

tsContent += `export interface CreateSessionRequest {\n  email: string;\n  password?: string;\n}\n\n`

tsContent += `export interface Organization {\n  orgId: UUIDv7;\n  name: string;\n  slug: string;\n  createdAt: ISODateTime;\n}\n\n`

tsContent += `export interface CreateOrganizationRequest {\n  name: string;\n  slug: string;\n}\n\n`

tsContent += `export interface Project {\n  projectId: UUIDv7;\n  orgId: UUIDv7;\n  title: string;\n  description?: string;\n  createdAt: ISODateTime;\n}\n\n`

tsContent += `export interface CreateProjectRequest {\n  title: string;\n  description?: string;\n}\n\n`

tsContent += `export interface ResponseMeta {\n  requestId: string;\n  nextCursor?: string | null;\n  totalCount?: number | null;\n}\n\n`

tsContent += `export interface ErrorEnvelope {\n  error: {\n    code:\n      | 'validation_failed'\n      | 'authentication_required'\n      | 'permission_denied'\n      | 'not_found'\n      | 'conflict_stale_version'\n      | 'rate_limited'\n      | 'research_provider_unavailable'\n      | 'research_provider_rate_limited'\n      | 'model_provider_error'\n      | 'rejected_output'\n      | 'internal_error';\n    message: string;\n    requestId: string;\n    retryable: boolean;\n    details?: Array<{ field?: string; issue?: string }>;\n  };\n}\n\n`

tsContent += `export interface Operations {\n`
const paths = spec.paths || {}
for (const [pathKey, pathItem] of Object.entries(paths)) {
  for (const method of ['get', 'post', 'put', 'delete', 'patch']) {
    if (pathItem[method]) {
      const op = pathItem[method]
      tsContent += `  ${op.operationId}: { method: '${method.toUpperCase()}'; path: '${pathKey}' };\n`
    }
  }
}
tsContent += `}\n`

fs.writeFileSync(path.join(tsOutDir, 'index.ts'), tsContent, 'utf-8')
console.log('✅ Generated TypeScript client contracts at', path.join(tsOutDir, 'index.ts'))

// 2. Generate Python Types & Client
fs.mkdirSync(pyOutDir, { recursive: true })

let pyContent = `${doNotEditPy}from __future__ import annotations
from typing import Literal, Optional, List, Dict, Any
from pydantic import BaseModel, Field

UUIDv7 = str
ISODateTime = str

RunStatus = Literal[
    "queued",
    "claimed",
    "running",
    "retry_wait",
    "succeeded",
    "failed",
    "manual_retry",
    "cancelled",
]

UserRole = Literal["owner", "admin", "editor", "reviewer"]

class HealthResponse(BaseModel):
    status: str
    timestamp: ISODateTime
    version: str

class SessionContext(BaseModel):
    authenticated: bool
    userId: Optional[UUIDv7] = None
    email: Optional[str] = None
    activeOrgId: Optional[UUIDv7] = None
    role: Optional[UserRole] = None

class CreateSessionRequest(BaseModel):
    email: str
    password: Optional[str] = None

class Organization(BaseModel):
    orgId: UUIDv7
    name: str
    slug: str
    createdAt: ISODateTime

class CreateOrganizationRequest(BaseModel):
    name: str
    slug: str

class Project(BaseModel):
    projectId: UUIDv7
    orgId: UUIDv7
    title: str
    description: Optional[str] = None
    createdAt: ISODateTime

class CreateProjectRequest(BaseModel):
    title: str
    description: Optional[str] = None

class ResponseMeta(BaseModel):
    requestId: str
    nextCursor: Optional[str] = None
    totalCount: Optional[int] = None

class ErrorDetail(BaseModel):
    field: Optional[str] = None
    issue: Optional[str] = None

class ErrorPayload(BaseModel):
    code: str
    message: str
    requestId: str
    retryable: bool
    details: Optional[List[ErrorDetail]] = None

class ErrorEnvelope(BaseModel):
    error: ErrorPayload
`

fs.writeFileSync(path.join(pyOutDir, '__init__.py'), pyContent, 'utf-8')
console.log('✅ Generated Python client contracts at', path.join(pyOutDir, '__init__.py'))
