#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import { load } from 'js-yaml'

const root = process.cwd()
const openapiPath = path.join(root, 'packages', 'contracts', 'openapi.yaml')
const tsOutDir = path.join(root, 'packages', 'contracts', 'generated', 'typescript')
const pyOutDir = path.join(root, 'packages', 'contracts', 'generated', 'python')

if (!fs.existsSync(openapiPath)) {
  console.error(`❌ openapi.yaml not found at ${openapiPath}`)
  process.exit(1)
}

const spec = load(fs.readFileSync(openapiPath, 'utf-8'))

const doNotEditTs = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
 * Source: packages/contracts/openapi.yaml
 * Generated by: scripts/generate-clients.mjs
 */

`

const doNotEditPy = `"""
AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY.
Source: packages/contracts/openapi.yaml
Generated by: scripts/generate-clients.mjs
"""

`

// 1. Generate TypeScript Types & Client
fs.mkdirSync(tsOutDir, { recursive: true })

let tsContent = `${doNotEditTs}export type UUIDv7 = string;
export type ISODateTime = string;

export type RunStatus =
  | 'queued'
  | 'claimed'
  | 'running'
  | 'retry_wait'
  | 'succeeded'
  | 'failed'
  | 'manual_retry'
  | 'cancelled';

export type UserRole = 'owner' | 'admin' | 'editor' | 'reviewer';

export interface HealthResponse {
  status: string;
  timestamp: ISODateTime;
  version: string;
}

export interface SessionContext {
  authenticated: boolean;
  userId?: UUIDv7;
  email?: string;
  activeOrgId?: UUIDv7;
  role?: UserRole;
}

export interface CreateSessionRequest {
  email: string;
  password?: string;
}

export interface Organization {
  orgId: UUIDv7;
  name: string;
  slug: string;
  isDemo?: boolean;
  createdAt: ISODateTime;
}

export interface CreateOrganizationRequest {
  name: string;
  slug: string;
}

export interface Project {
  projectId: UUIDv7;
  orgId: UUIDv7;
  title: string;
  description?: string;
  isDemo?: boolean;
  createdAt: ISODateTime;
}

export interface CreateProjectRequest {
  title: string;
  description?: string;
}

export interface Invitation {
  invitationId: UUIDv7;
  orgId: UUIDv7;
  email: string;
  role: UserRole;
  status: 'pending' | 'accepted' | 'declined' | 'revoked' | string;
  createdAt: ISODateTime;
}

export interface CreateInvitationRequest {
  email: string;
  role: UserRole;
  projectGrants?: UUIDv7[];
}

export interface Membership {
  membershipId: UUIDv7;
  orgId: UUIDv7;
  userId: UUIDv7;
  email?: string;
  role: UserRole;
  active: boolean;
  projectGrants?: UUIDv7[];
  createdAt: ISODateTime;
}

export interface ImportArtifact {
  artifactId: UUIDv7;
  projectId: UUIDv7;
  filename: string;
  status: string;
  createdAt: ISODateTime;
}

export interface ParseRun {
  runId: UUIDv7;
  artifactId: UUIDv7;
  status: RunStatus;
  warnings?: Array<{ line?: number; message?: string }>;
  sceneCount?: number;
}

export interface ScriptVersion {
  versionId: UUIDv7;
  projectId: UUIDv7;
  versionNumber: number;
  revisionLabel: string;
  sceneCount?: number;
  itemCount?: number;
  createdAt: ISODateTime;
}

export interface Job {
  jobId: UUIDv7;
  status: RunStatus;
  jobType: string;
  progress?: number;
  error?: string;
  createdAt: ISODateTime;
}

export interface ClearanceItem {
  itemId: UUIDv7;
  projectId: UUIDv7;
  versionId?: UUIDv7;
  category: string;
  entityName: string;
  contextText?: string;
  status: string;
  disposition?: string;
  assignedTo?: UUIDv7;
  dueDate?: ISODateTime;
  claimCount?: number;
}

export interface SourceSnapshot {
  snapshotId: UUIDv7;
  url: string;
  retrievedAt: ISODateTime;
  publisher: string;
  tier: string;
  excerpt?: string;
}

export interface EvidenceClaim {
  claimId: UUIDv7;
  snapshotId: UUIDv7;
  claimText: string;
  stance: string;
  confidence?: number;
}

export interface ItemEvidence {
  itemId: UUIDv7;
  claims: EvidenceClaim[];
  snapshots: SourceSnapshot[];
}

export interface RecordDecisionRequest {
  decision: 'cleared' | 'flagged' | 'rejected' | 'further_review' | string;
  rationale: string;
  expectedVersion?: number;
}

export interface Referral {
  referralId: UUIDv7;
  itemId: UUIDv7;
  targetRole: string;
  question: string;
  response?: string;
  status: string;
}

export interface Comment {
  commentId: UUIDv7;
  itemId?: UUIDv7;
  authorId: UUIDv7;
  authorEmail?: string;
  body: string;
  parentId?: UUIDv7;
  createdAt: ISODateTime;
}

export interface RewriteProposal {
  proposalId: UUIDv7;
  itemId: UUIDv7;
  proposedText: string;
  rationale?: string;
  status: 'proposed' | 'approved' | 'rejected' | 'withdrawn' | string;
}

export interface MonitoringPolicy {
  projectId: UUIDv7;
  cadence: string;
  active: boolean;
  lastRunAt?: ISODateTime;
}

export interface MonitoringRun {
  runId: UUIDv7;
  projectId: UUIDv7;
  status: RunStatus;
  itemsChecked: number;
  changesDetected: number;
  createdAt: ISODateTime;
}

export interface Notification {
  notificationId: UUIDv7;
  orgId: UUIDv7;
  title: string;
  body: string;
  read: boolean;
  link?: string;
  createdAt: ISODateTime;
}

export interface AuditRecord {
  recordId: UUIDv7;
  orgId: UUIDv7;
  projectId?: UUIDv7;
  eventType: string;
  actorId: UUIDv7;
  actorEmail?: string;
  payload?: Record<string, any>;
  receiptHash?: string;
  timestamp: ISODateTime;
}

export interface ReportPreview {
  projectId: UUIDv7;
  totalItems: number;
  clearedItems: number;
  flaggedItems: number;
  unresolvedRisk: number;
  categories?: Array<{ category?: string; count?: number }>;
}

export interface ReportSnapshot {
  snapshotId: UUIDv7;
  projectId: UUIDv7;
  versionId: UUIDv7;
  generatedAt: ISODateTime;
  status: string;
}

export interface ReportRelease {
  releaseId: UUIDv7;
  snapshotId: UUIDv7;
  releasedBy: UUIDv7;
  releasedAt: ISODateTime;
  downloadUrl?: string;
}

export interface ResponseMeta {
  requestId: string;
  nextCursor?: string | null;
  totalCount?: number | null;
}

export interface ApiError {
  code:
    | 'validation_failed'
    | 'authentication_required'
    | 'permission_denied'
    | 'not_found'
    | 'conflict_stale_version'
    | 'rate_limited'
    | 'research_provider_unavailable'
    | 'research_provider_rate_limited'
    | 'model_provider_error'
    | 'rejected_output'
    | 'internal_error'
    | string;
  message: string;
  requestId?: string;
  retryable?: boolean;
  details?: Array<{ field?: string; issue?: string }>;
}

export interface ErrorEnvelope {
  error: ApiError;
}

export type ApiResult<T, E extends ApiError = ApiError> =
  | { ok: true; value: T }
  | { ok: false; error: E };

export interface ApiClientConfig {
  baseUrl?: string;
  fetch?: typeof fetch;
}

async function request<T>(
  baseUrl: string,
  fetchFn: typeof fetch,
  method: string,
  path: string,
  options: {
    params?: Record<string, string | number | boolean | undefined>;
    query?: Record<string, string | number | boolean | undefined>;
    body?: any;
    headers?: Record<string, string>;
  } = {}
): Promise<ApiResult<T>> {
  let resolvedPath = path;
  if (options.params) {
    for (const [k, v] of Object.entries(options.params)) {
      resolvedPath = resolvedPath.replace(\`{\${k}}\`, encodeURIComponent(String(v)));
    }
  }

  const url = new URL(resolvedPath.startsWith('http') ? resolvedPath : \`\${baseUrl}\${resolvedPath}\`, typeof window !== 'undefined' ? window.location.origin : 'http://localhost:8000');
  
  if (options.query) {
    for (const [k, v] of Object.entries(options.query)) {
      if (v !== undefined) {
        url.searchParams.append(k, String(v));
      }
    }
  }

  const headers: Record<string, string> = {
    'Accept': 'application/json',
    ...(options.headers || {})
  };

  let bodyStr: string | undefined = undefined;
  if (options.body !== undefined) {
    headers['Content-Type'] = 'application/json';
    bodyStr = JSON.stringify(options.body);
  }

  try {
    const res = await fetchFn(url.toString(), {
      method,
      headers,
      body: bodyStr,
      credentials: 'include'
    });

    if (res.status === 204) {
      return { ok: true, value: undefined as unknown as T };
    }

    const json = await res.json().catch(() => null);

    if (!res.ok) {
      const apiErr: ApiError = (json && json.error) ? json.error : {
        code: res.status === 401 ? 'authentication_required' : res.status === 403 ? 'permission_denied' : res.status === 404 ? 'not_found' : 'internal_error',
        message: (json && (json.message || json.detail)) || res.statusText || 'Request failed',
        requestId: (json && json.error && json.error.requestId) || res.headers.get('x-request-id') || '',
        retryable: res.status >= 500
      };
      return { ok: false, error: apiErr };
    }

    const data = (json && json.data !== undefined) ? json.data : json;
    return { ok: true, value: data as T };
  } catch (err: any) {
    return {
      ok: false,
      error: {
        code: 'internal_error',
        message: err?.message || 'Network request failed',
        retryable: true
      }
    };
  }
}
`

// Generate operations mapping and client methods
const operationsList = []
const paths = spec.paths || {}
for (const [pathKey, pathItem] of Object.entries(paths)) {
  for (const method of ['get', 'post', 'put', 'delete', 'patch']) {
    if (pathItem[method]) {
      const op = pathItem[method]
      operationsList.push({
        id: op.operationId,
        method: method.toUpperCase(),
        path: pathKey,
        summary: op.summary || '',
      })
    }
  }
}

tsContent += `\nexport interface Operations {\n`
for (const op of operationsList) {
  tsContent += `  ${op.id}: { method: '${op.method}'; path: '${op.path}' };\n`
}
tsContent += `}\n\n`

tsContent += `export function createApiClient(config: ApiClientConfig = {}) {\n`
tsContent += `  const baseUrl = config.baseUrl || '';\n`
tsContent += `  const fetchFn = config.fetch || (typeof window !== 'undefined' ? window.fetch.bind(window) : fetch);\n\n`
tsContent += `  return {\n`

for (const op of operationsList) {
  const pathParams = (op.path.match(/{([^}]+)}/g) || []).map(p => p.slice(1, -1))
  const isPostOrPut = ['POST', 'PUT', 'PATCH'].includes(op.method)
  
  tsContent += `    /** ${op.summary} */\n`
  tsContent += `    ${op.id}: async (\n`
  tsContent += `      args${pathParams.length > 0 || isPostOrPut ? '' : '?'}: {\n`
  if (pathParams.length > 0) {
    tsContent += `        params: { ${pathParams.map(p => `${p}: string`).join('; ')} };\n`
  }
  if (op.id === 'listClearanceItems') {
    tsContent += `        query?: { category?: string; status?: string };\n`
  } else {
    tsContent += `        query?: Record<string, string | number | boolean | undefined>;\n`
  }
  if (isPostOrPut) {
    tsContent += `        body?: any;\n`
    tsContent += `        idempotencyKey?: string;\n`
  }
  tsContent += `        headers?: Record<string, string>;\n`
  tsContent += `      }\n`
  tsContent += `    ): Promise<ApiResult<any>> => {\n`
  tsContent += `      const headers: Record<string, string> = { ...(args?.headers || {}) };\n`
  if (isPostOrPut) {
    tsContent += `      if (args && 'idempotencyKey' in args && args.idempotencyKey) {\n`
    tsContent += `        headers['Idempotency-Key'] = args.idempotencyKey;\n`
    tsContent += `      }\n`
  }
  tsContent += `      return request(baseUrl, fetchFn, '${op.method}', '${op.path}', {\n`
  tsContent += `        params: args && 'params' in args ? (args as any).params : undefined,\n`
  tsContent += `        query: args?.query,\n`
  tsContent += `        body: args && 'body' in args ? (args as any).body : undefined,\n`
  tsContent += `        headers,\n`
  tsContent += `      });\n`
  tsContent += `    },\n\n`
}

tsContent += `  };\n`
tsContent += `}\n\n`
tsContent += `export const api = createApiClient();\n`

fs.writeFileSync(path.join(tsOutDir, 'index.ts'), tsContent, 'utf-8')
console.log('✅ Generated TypeScript client contracts at', path.join(tsOutDir, 'index.ts'))

// 2. Generate Python Types & Client
fs.mkdirSync(pyOutDir, { recursive: true })

let pyContent = `${doNotEditPy}from __future__ import annotations
from typing import Literal, Optional, List, Dict, Any
from pydantic import BaseModel, Field

UUIDv7 = str
ISODateTime = str

RunStatus = Literal[
    "queued",
    "claimed",
    "running",
    "retry_wait",
    "succeeded",
    "failed",
    "manual_retry",
    "cancelled",
]

UserRole = Literal["owner", "admin", "editor", "reviewer"]

class HealthResponse(BaseModel):
    status: str
    timestamp: ISODateTime
    version: str

class SessionContext(BaseModel):
    authenticated: bool
    userId: Optional[UUIDv7] = None
    email: Optional[str] = None
    activeOrgId: Optional[UUIDv7] = None
    role: Optional[UserRole] = None

class CreateSessionRequest(BaseModel):
    email: str
    password: Optional[str] = None

class Organization(BaseModel):
    orgId: UUIDv7
    name: str
    slug: str
    isDemo: Optional[bool] = False
    createdAt: ISODateTime

class CreateOrganizationRequest(BaseModel):
    name: str
    slug: str

class Project(BaseModel):
    projectId: UUIDv7
    orgId: UUIDv7
    title: str
    description: Optional[str] = None
    isDemo: Optional[bool] = False
    createdAt: ISODateTime

class CreateProjectRequest(BaseModel):
    title: str
    description: Optional[str] = None

class Invitation(BaseModel):
    invitationId: UUIDv7
    orgId: UUIDv7
    email: str
    role: UserRole
    status: str
    createdAt: ISODateTime

class CreateInvitationRequest(BaseModel):
    email: str
    role: UserRole
    projectGrants: Optional[List[UUIDv7]] = None

class Membership(BaseModel):
    membershipId: UUIDv7
    orgId: UUIDv7
    userId: UUIDv7
    email: Optional[str] = None
    role: UserRole
    active: bool
    projectGrants: Optional[List[UUIDv7]] = None
    createdAt: ISODateTime

class ImportArtifact(BaseModel):
    artifactId: UUIDv7
    projectId: UUIDv7
    filename: str
    status: str
    createdAt: ISODateTime

class ParseRun(BaseModel):
    runId: UUIDv7
    artifactId: UUIDv7
    status: RunStatus
    warnings: Optional[List[Dict[str, Any]]] = None
    sceneCount: Optional[int] = None

class ScriptVersion(BaseModel):
    versionId: UUIDv7
    projectId: UUIDv7
    versionNumber: int
    revisionLabel: str
    sceneCount: Optional[int] = None
    itemCount: Optional[int] = None
    createdAt: ISODateTime

class Job(BaseModel):
    jobId: UUIDv7
    status: RunStatus
    jobType: str
    progress: Optional[float] = None
    error: Optional[str] = None
    createdAt: ISODateTime

class ClearanceItem(BaseModel):
    itemId: UUIDv7
    projectId: UUIDv7
    versionId: Optional[UUIDv7] = None
    category: str
    entityName: str
    contextText: Optional[str] = None
    status: str
    disposition: Optional[str] = None
    assignedTo: Optional[UUIDv7] = None
    dueDate: Optional[ISODateTime] = None
    claimCount: Optional[int] = None

class SourceSnapshot(BaseModel):
    snapshotId: UUIDv7
    url: str
    retrievedAt: ISODateTime
    publisher: str
    tier: str
    excerpt: Optional[str] = None

class EvidenceClaim(BaseModel):
    claimId: UUIDv7
    snapshotId: UUIDv7
    claimText: str
    stance: str
    confidence: Optional[float] = None

class ItemEvidence(BaseModel):
    itemId: UUIDv7
    claims: List[EvidenceClaim] = []
    snapshots: List[SourceSnapshot] = []

class RecordDecisionRequest(BaseModel):
    decision: str
    rationale: str
    expectedVersion: Optional[int] = None

class Referral(BaseModel):
    referralId: UUIDv7
    itemId: UUIDv7
    targetRole: str
    question: str
    response: Optional[str] = None
    status: str

class Comment(BaseModel):
    commentId: UUIDv7
    itemId: Optional[UUIDv7] = None
    authorId: UUIDv7
    authorEmail: Optional[str] = None
    body: str
    parentId: Optional[UUIDv7] = None
    createdAt: ISODateTime

class RewriteProposal(BaseModel):
    proposalId: UUIDv7
    itemId: UUIDv7
    proposedText: str
    rationale: Optional[str] = None
    status: str

class MonitoringPolicy(BaseModel):
    projectId: UUIDv7
    cadence: str
    active: bool
    lastRunAt: Optional[ISODateTime] = None

class MonitoringRun(BaseModel):
    runId: UUIDv7
    projectId: UUIDv7
    status: RunStatus
    itemsChecked: int
    changesDetected: int
    createdAt: ISODateTime

class Notification(BaseModel):
    notificationId: UUIDv7
    orgId: UUIDv7
    title: str
    body: str
    read: bool
    link: Optional[str] = None
    createdAt: ISODateTime

class AuditRecord(BaseModel):
    recordId: UUIDv7
    orgId: UUIDv7
    projectId: Optional[UUIDv7] = None
    eventType: str
    actorId: UUIDv7
    actorEmail: Optional[str] = None
    payload: Optional[Dict[str, Any]] = None
    receiptHash: Optional[str] = None
    timestamp: ISODateTime

class ReportPreview(BaseModel):
    projectId: UUIDv7
    totalItems: int
    clearedItems: int
    flaggedItems: int
    unresolvedRisk: int
    categories: Optional[List[Dict[str, Any]]] = None

class ReportSnapshot(BaseModel):
    snapshotId: UUIDv7
    projectId: UUIDv7
    versionId: UUIDv7
    generatedAt: ISODateTime
    status: str

class ReportRelease(BaseModel):
    releaseId: UUIDv7
    snapshotId: UUIDv7
    releasedBy: UUIDv7
    releasedAt: ISODateTime
    downloadUrl: Optional[str] = None

class ResponseMeta(BaseModel):
    requestId: str
    nextCursor: Optional[str] = None
    totalCount: Optional[int] = None

class ErrorDetail(BaseModel):
    field: Optional[str] = None
    issue: Optional[str] = None

class ErrorPayload(BaseModel):
    code: str
    message: str
    requestId: str
    retryable: bool
    details: Optional[List[ErrorDetail]] = None

class ErrorEnvelope(BaseModel):
    error: ErrorPayload
`

fs.writeFileSync(path.join(pyOutDir, '__init__.py'), pyContent, 'utf-8')
console.log('✅ Generated Python client contracts at', path.join(pyOutDir, '__init__.py'))
