"""Persist research step receipts for agent tool execution and replay.

Stores immutable step receipts generated by the agentic research orchestrator
during clearance item investigation. Each step receipt captures the exact tool
name, canonical SHA256 input/output hashes, JSON payloads, execution status,
and timing.

Unique constraints enforce monotonic ordering per run attempt and deterministic
replay deduplication by canonical input hash. Multi-tenant foreign keys ensure
strict isolation to (org_id, project_id).

Revision ID: 0040_research_step_receipts
Revises: 0039_monitoring_deltas
Create Date: 2026-09-14 00:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB

revision: str = "0040_research_step_receipts"
down_revision: str | None = "0039_monitoring_deltas"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# JSONB on PostgreSQL, plain JSON on SQLite
_JSON = sa.JSON().with_variant(JSONB(), "postgresql")


def upgrade() -> None:
    op.create_table(
        "research_step_receipts",
        sa.Column("id", sa.UUID(as_uuid=True), primary_key=True),
        sa.Column("org_id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("project_id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "run_id",
            sa.UUID(as_uuid=True),
            sa.ForeignKey("research_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "item_id",
            sa.UUID(as_uuid=True),
            sa.ForeignKey("clearance_items.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("job_id", sa.UUID(as_uuid=True), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(100), nullable=False),
        sa.Column("tool_input_hash", sa.String(64), nullable=False),
        sa.Column("tool_output_hash", sa.String(64), nullable=False),
        sa.Column("input_payload", _JSON, nullable=True),
        sa.Column("output_payload", _JSON, nullable=True),
        sa.Column("status", sa.String(50), nullable=False, server_default="succeeded"),
        sa.Column("duration_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id", "project_id"],
            ["projects.org_id", "projects.id"],
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "run_id",
            "attempt_number",
            "step_index",
            name="uq_research_step_receipts_run_step",
        ),
        sa.UniqueConstraint(
            "run_id",
            "attempt_number",
            "tool_name",
            "tool_input_hash",
            name="uq_research_step_receipts_replay",
        ),
        sa.CheckConstraint("step_index >= 0", name="ck_step_receipts_step_index"),
        sa.CheckConstraint("length(tool_input_hash) = 64", name="ck_step_receipts_input_hash"),
        sa.CheckConstraint("length(tool_output_hash) = 64", name="ck_step_receipts_output_hash"),
    )
    op.create_index(
        "idx_research_step_receipts_scope",
        "research_step_receipts",
        ["org_id", "project_id", "run_id"],
    )
    op.create_index(
        "idx_research_step_receipts_item",
        "research_step_receipts",
        ["org_id", "project_id", "item_id"],
    )


def downgrade() -> None:
    op.drop_index(
        "idx_research_step_receipts_item",
        table_name="research_step_receipts",
    )
    op.drop_index(
        "idx_research_step_receipts_scope",
        table_name="research_step_receipts",
    )
    op.drop_table("research_step_receipts")
